import { Github } from "lucide-react";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import type { FC, ReactNode } from "react";
import { cn } from "~/lib/utils";

interface LayoutProps {
  children: ReactNode;
}

export const LandingLayout: FC<LayoutProps> = ({ children }) => {


  const { data: sessionData } = useSession();

  return (
    <div className="relative h-screen w-screen overflow-x-hidden bg-slate-950 p-3 py-3 pr-3 pt-16">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="absolute left-0 top-0 flex h-16 w-full items-center justify-between bg-slate-950 px-6 text-white">
        <div className="">
          <h1 className="text-3xl font-bold">MemoMate</h1>
        </div>
        <div className="text-xl font-bold">GitHub</div>
        <div
          className={cn(
            "group absolute left-1/2 top-full z-10 flex h-14 -translate-x-1/2 transform items-center rounded-b-3xl bg-slate-950 px-6 transition-all ease-in-out hover:bg-slate-800 md:h-20"
          )}
          onClick={()=>void signIn()}
        >
          <div className="pointer-events-none absolute -left-[1.7rem] top-0 z-20 h-7 w-7 bg-slate-950 transition-all ease-in-out group-hover:bg-slate-800">
            <div className="absolute right-[.06rem] h-full w-8 rounded-se-3xl bg-slate-50"></div>
          </div>
          <div className="pointer-events-none absolute -right-[1.7rem] top-0 z-20 h-7 w-7 bg-slate-950 pl-[.05rem] transition-all ease-in-out group-hover:bg-slate-800">
            <div className="absolute h-full w-8 rounded-ss-3xl bg-slate-50"></div>
          </div>
          <p className="flex gap-2 text-sm md:text-base">
            <Github /> Sign up{" "}
            <span className="hidden font-semibold md:inline">with GitHub</span>
          </p>
        </div>
      </header>
      <main className="h-full rounded-3xl bg-slate-50 px-3">{children}</main>
    </div>
  );
};
